### ISSUE TITLE
Install issue on ARM architecture Linux?

### ISSUE THREAD

**Issue by jsmarsha11** [oscarhiggott/PyMatching#75] opened 2023-08-14 18:28 UTC
Have tried to install from pip or from source on an ARM architecture but find the install fails due to incorrect compiler flags(?). I also couldn't figure out how to directly modify setup.py or CMakeLists.txt to install from source (modifying ARCH_OPT did not seem to resolve it for example).

System: aarch64 architecture, Ubuntu 22.04, pip 23.2.1, Python 3.10.6, gcc 12.3.0.

The error message I get from pip is (similar error from running setup.py directly though):

-- Configuring done (6.5s)
      -- Generating done (0.1s)
      -- Build files have been written to: /tmp/pip-install-b2m5hx1q/pymatching_6425e3cee2c34cdc8bdce779dc386c44/build/temp.linux-aarch64-cpython-310/pymatching._cpp_pymatching
      [  0%] Building CXX object build/temp.linux-aarch64-cpython-310/pymatching._cpp_pymatching/_deps/stim-src/CMakeFiles/libstim.dir/src/stim.cc.o
      c++: error: unrecognized command-line option ‘-mno-avx2’
      c++: error: unrecognized command-line option ‘-msse2’
      gmake[3]: *** [build/temp.linux-aarch64-cpython-310/pymatching._cpp_pymatching/_deps/stim-src/CMakeFiles/libstim.dir/build.make:76: build/temp.linux-aarch64-cpython-310/pymatching._cpp_pymatching/_deps/stim-src/CMakeFiles/libstim.dir/src/stim.cc.o] Error 1
      gmake[2]: *** [CMakeFiles/Makefile2:423: build/temp.linux-aarch64-cpython-310/pymatching._cpp_pymatching/_deps/stim-src/CMakeFiles/libstim.dir/all] Error 2
      gmake[1]: *** [CMakeFiles/Makefile2:273: CMakeFiles/_cpp_pymatching.dir/rule] Error 2
      gmake: *** [Makefile:218: _cpp_pymatching] Error 2

Any assistance would be appreciated! Hopefully it isn't just an issue due to how my system is set-up. Thanks!

**Comment by oscarhiggott** [comment] 2023-08-14 18:34
I'm closing this as it seems to be a duplicate of issue #65. As mentioned in #65 you could try the old (slower) version of pymatching with `pip install PyMatching==0.7.0` until this issue is fixed.

**Closed by oscarhiggott** 2023-08-14 18:34 UTC
